kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wildfly-kubeping-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: wildfly-kubeping-service-account
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wildfly-kubeping-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wildfly-kubeping-pod-reader
subjects:
- kind: ServiceAccount
  name: wildfly-kubeping-service-account
  namespace: default