kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wildfly-kubeping-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: wildfly-kubeping-api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wildfly-kubeping-pod-reader
subjects:
- kind: ServiceAccount
  name: wildfly-kubeping-service-account
  namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-kube-cluster
spec:
  selector:
    matchLabels:
      app: wildfly-kube-cluster
  replicas: 2
  template: 
    metadata:
      labels:
        app: wildfly-kube-cluster
    spec:
      serviceAccountName: wildfly-kubeping-service-account
      containers:
        - name: wildfly-kube-cluster
          image: yonoos/wildfly-kube-cluster:latest
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 800Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 7600 #jgroups default
            - containerPort: 8888 #jgroups undertow
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP            
