apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-kube-cluster
spec:
  selector:
    matchLabels:
      app: wildfly-kube-cluster
  replicas: 3
  template: 
    metadata:
      labels:
        app: wildfly-kube-cluster
    spec:
      serviceAccountName: wildfly-kubeping-service-account
      containers:
        - name: wildfly-kube-cluster
          image: fra.ocir.io/wexlog2018/yonoos/wildfly-kube-cluster:latest
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 800Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 7600 #jgroups default
            - containerPort: 8888 #jgroups undertow
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  name: wildfly-kube-cluster-service
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: wildfly-kube-cluster